# Generated by Django 4.2.7 on 2024-03-04 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_alter_task_documentid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='documentId',
            field=models.PositiveBigIntegerField(),
        ),
    ]
